### ISSUE TITLE
[Tarea 1]Duda enunciado pregunta 2 parte 1 assembly

### ISSUE THREAD

**Issue by juakoke** [IIC2343/Syllabus-2022-1-S1#1]
Me surgieron 2 dudas en el enunciado:
- Cuando dice que recibimos 2 tuplas de coordenadas en un espacio cartesiano, donde por ejemplo nos dan el numero de aristas 4, y nos dan 4 coordenadas para estas es correcto que sean aristas y no vertices?, pasa que me imagino uniendo estos 4 puntos por ejemplo una piramide en base triangular tiene 4 vertices pero 6 aristas, entonces no logro ver las aristas. 
- En segundo lugar nos piden calcular el centroide para ambas figuras pero solo tenemos que devolver un output, ¿Este output es el centroide entre ambas figuras finalmente o el centroide de alguna de las 2 figuras?, En caso de ser el centroide entre ambas figuras, ¿Podemos asumir que ambas figuras tendran el mismo volumen?

**Comment by Cristofernandez** [comment]
Hola, leyendo el enunciado me quedo la misma duda.

**Comment by tocococa** [comment]
Hola @juakoke, @Cristofernandez, efectivamente debería decir vértices en lugar de aristas, vamos a actualizar el enunciado.

Sobre el centroide, deben entregar un solo número que corresponde al centroide del cuerpo completo, como no tienen la función de densidad, esta sería 1 y el peso de cada figura corresponde al área, para que puedan calcular el centroide de ambas figuras.

**Comment by juakoke** [comment]
Muchas gracias @tocococa, en la segunda parte con respecto al área me queda nuevamente una pregunta. Cuando hablas del área de la figura, al ser un espacio tridimensional, ¿Asumimos como el peso de la figura la sumatoria de las áreas de todas sus caras?, Me surge esta pregunta porque no se fija una restricción en el enunciado de número de vértices por figura que nos podrían entregar, entonces me imagino que podríamos recibir desde un triángulo en un plano hasta alguna figura de muchos vértices.

**Comment by tocococa** [comment]
@juakoke perdón, estaba pensando en 2D cuando respondí tu pregunta, en el enunciado ahora quedó más claro, pero tienes que considerar que la densidad es igual y constante para ambas figuras, por lo que el centro de masa de ambas juntas sería un promedio ponderado entre sus centroides.

**Comment by juakoke** [comment]
@tocococa ahi leí el enunciado nuevamente pero, a lo que me refiero es justo a lo que mencionas, como el centroide entre ambas figuras es el promedio ponderado de sus centroides y tenemos densidad constante, necesitamos el volumen de estas, pero como no nos restringen el numero de vertices que se nos puede entregar, ej: 20 vertices, tendriamos que hacer muchos casos de calculo del volumen para diferentes cantidades de vertices que se nos pudieran entregar, es esto correcto o lo estoy viendo mal?

**Comment by tocococa** [comment]
Si, eso es correcto, igual es razonable asumir que no vamos a preguntarles por figuras con cientos de caras, alrededor de un dodecaedro sería el límite.

**Comment by inarrgd** [comment]
Hola!
No entiendo cómo calcular el área. Hay que tener una "función" para cada tipo de figura? Lo pregunto porque si nos entregan desde tetraedro hasta dodecaedro (cualquier poliedro desde 4 hasta 12 caras), cada una tiene una forma distinta de calcular el área, por lo que habría que tener implementadas 9 maneras distintas de calcular el área para todos los casos? No entiendo la verdad si se pide que hagamos automático el cálculo para cualquier poliedro que se nos entregue, o si estoy entendiendo mal.

Gracias!

**Comment by tocococa** [comment]
Hola @inarrgd, para calcular el centroide de un polígono convexo con n vértices (x_1,y_1, ..., x_n,y_n) (puedes asumir que solo recibirás figuras de este estilo), existe una fórmula general para calcularlo, que consta de 3 sumatorias:
![image](https://user-images.githubusercontent.com/22779371/162109380-ad374943-5bd9-4852-8e6e-cc1e9a06c04b.png)
![image](https://user-images.githubusercontent.com/22779371/162109399-64e73090-21d6-4b80-8fba-706f104d8023.png)
donde A corresponde a 
![image](https://user-images.githubusercontent.com/22779371/162109425-03a7c08f-c89f-4cba-8c1a-e5acb3ae8290.png)

Con esto no tienes que intentar adivinar que polígono es el input ni escribir x fórmulas diferentes.

**Comment by inarrgd** [comment]
Gracias @tocococa!
Aún así, me queda la duda, porque esas fórmulas son para un polígono como tu indicas, que es una figura bidimensional, pero las figuras tridimensionales (poliedros) no podrían considerarse con esa fórmula. Me queda la duda..., o lo estoy viendo mal?
