### ISSUE TITLE
[Tarea 1] Consideraciones Pregunta 2.1

### ISSUE THREAD

**Issue by jbulness** [IIC2343/Syllabus-2022-1-S1#11]
Hola, quería saber qué cosas podemos considerar o asumir en la pregunta 2.1, debido a que en otra issue hay un comentario sobre que podemos asumir que las figuras no van a tener más de 12 vértices. ¿Podemos asumir que todas las figuras van a ser regulares? ¿que las coordenadas van a ser números naturales? ¿qué consideraciones debemos tener?

**Comment by tocococa** [comment]
Hola @jbulness, si, no puedes asumir que son regulares pero si puedes asumir que van a ser convexas, revisa la issue #1 si tienes más dudas, y las coordenadas van a ser enteros positivos.

**Comment by jbulness** [comment]
Ok, gracias @tocococa!
