### ISSUE TITLE
[Tarea 1] Duda cálculo centroide 2.1

### ISSUE THREAD

**Issue by DomingoCarvajal** [IIC2343/Syllabus-2022-1-S1#12]
Hola! Todavía no me queda claro ciertos supuestos de la pregunta 2.1

Para el cálculo del centroide de ambas figuras debemos calcular la masa de las figuras? Se dijo en la issue #5 que la densidad de las figuras era la misma pero eso no significa que la masa sea la misma, por lo que para calcular el centroide tendríamos que calcular el área/volumen de cada figura, lo que hace que se complique mucho el cálculo. Me haría más sentido que la masa sea la misma en ambas figuras.

Además, según el script de ejemplo en el enunciado, podemos tener 3 vértices, lo que haría una figura plana sin volumen. Y también podemos tener 4 vértices, que podrían hacer un cuerpo con volumen. Por lo que no me queda muy claro como podríamos calcular y comparar estas masas.

Agradecería que nos dieran la fórmula exacta a calcular, ya que la complejidad del trabajo está en pasar esa fórmula a RISC-V. O también nos ayudaría que nos den ejemplos de como se calcularía el centroide para un caso en particular.

**Comment by tocococa** [comment]
Hola

En el caso de la figura plana de 3 vértices, el centroide se puede calcular como la intersección de sus alturas.

Cuando se trata de una figura convexa con volumen, los pasos serían:

1. Recorrer todos los vértices y obtener el mínimo y máximo para cada coordenada.
2. Lo anterior crea un bounding box para la figura, y a partir de eso se escoge un punto en su interior.
3. A partir del punto escogido anteriormente, particionar una nueva figura de 4 lados a cada una de las caras del poliedro anterior.
4. Separar cada cara en triángulos y definir un tetraedro irregular desde el punto central hacia cada partición de la cara.
5. El centroide de un tetraedro irregular se calcula de acuerdo a la fórmula ![image](https://user-images.githubusercontent.com/22779371/162769387-61be1b15-eb08-43b9-96e6-92b3578d2c45.png).
6. Su volumen es ![image](https://user-images.githubusercontent.com/22779371/162769535-fb683ebc-32c6-4933-bef5-d776343175fa.png)

7. Con el volumen y el centroide de cada tetraedro irregular, puden calcular el promedio ponderado para obtener el centroide de cada figura.

**Comment by Afro27** [comment]
En el caso de los test de ejemplo que hay 2 "cuerpos" de 3 vértices, se debe obtener el centroide entre ambas figuras? ya que las 2 tienen masa 0. 
Y en el caso del test 2 en el que hay un cuerpo de 3 vértices y otro de 8 vértices habría que calcular el centro de masa entre un cuerpo con masa 0 y otro con masa x, por lo que deberíamos solo devolver como output el centro de masa del segundo cuerpo?

**Comment by tocococa** [comment]
Hoola @Afro27, para el caso de las figuras planas, se debe calcular su centroide y el centroide entre ambas sería considerando un ponderador igual para cada una. En el test 2, el output efectivamente sería sólo el centroide del segundo cuerpo.

Ojo que el centroide es el centro geométrico de la figura, que coincide con el centro de masa para figuras tridimensionales.
