### ISSUE TITLE
[Tarea 1] Cálculo nota con atraso

### ISSUE THREAD

**Issue by manearaya** [IIC2343/Syllabus-2022-1-S1#13]
Hola!

Al entregar la tarea hoy la nota máxima es un 5.5, pero con esto se refieren a:

1. Que sea cual sea la nota que me saque, se le resta 1.5 puntos. 
Por ejemplo, me saco 3 puntos en la tarea -> mi nota sin atraso es un 4 -> mi nota con atraso es un 2.5

2. Que si me saco una nota mayor a 5.5, la nota final es un 5.5. 
Por ejemplo, me saco 3 puntos -> mi nota con y sin atraso es un 4
o me saco 6 puntos  en la tarea-> mi nota sin atraso es un 7 -> mi nota con atraso es un 5.5

3. Algún otro cálculo

Muchas gracias de antemano!

**Comment by tocococa** [comment]
Hola @manearaya, la nota con atraso se calcula según la fórmula `min{NT,5.5}`, donde NT es la nota de tu tarea, lo que seria como lo que planteas en el punto 2.
