### ISSUE TITLE
[Interrogación 1] Contenido que entra

### ISSUE THREAD

**Issue by Baelfire18** [IIC2343/Syllabus-2022-1-S1#14]
Hola! Hasta que [capítulo de los apuntes de github](https://github.com/IIC2343/Syllabus-2022-1-S1/tree/main/Apuntes) entra para la prueba?

**Comment by tocococa** [comment]
Hola @Baelfire18, perdón por lo tarde de la respuesta, pero debería ser más o menos todo el capítulo 1 y 2. Ojo que los apuntes a veces ven cosas en harta más profundidad que el curso.
