### ISSUE TITLE
[TAREA 2] Comportamiento extraño en codigo tarea

### ISSUE THREAD

**Issue by juakoke** [IIC2343/Syllabus-2022-1-S1#15]
Tengo una duda en el codigo que se nos entregó,  la linea 56 y 57 actualmente dicen "mv t6, t2" y luego "li t6, 4" respectivamente. Leyendo el codigo si no me equivoco la linea numero 56 debería decir "mv t5, t2" ya que es t5 quien luego se usa para movernos hacia el offset correcto en las direcciones continuas, ¿Esta esto correcto en el codigo?

**Comment by tocococa** [comment]
Hola @juakoke, correcto, debiese decir t5 en lugar de t6, altiro corrijo el script.

**Comment by tocococa** [comment]
Emmm, ya, si, entiendo de donde viene la confusión y fue error mio porque se incrementa tanto el contador como la dirección base de la que se lee.

Acabo de subir una corrección y _creo_ que ahora debería hacer todo OK.

Gracias por las observaciones.

**Comment by cotefon** [comment]
Hola! no sé que pasó, pero ayer el hit rate era de 23/24 y al descargar nuevamente la tarea ahora es como muestra en la imagen. Ese cache hit rate es sin hacerle nada a la tarea (solo he puesto comentarios)


![tarea 2](https://user-images.githubusercontent.com/37127700/165582740-1e3c1c83-8e35-4aa3-825f-47eb5c557bb0.png)

**Comment by tocococa** [comment]
Hola @cotefon, dame un ratito que ahora no lo puedo ver, pero voy a revisar bien que cambios hice según las sugerencias de @juakoke y voy a revisar que puede haber pasado, de todas formas debiese ser posible mejorar un poco el hitrate que estás viendo ahí, como de 86% a 100% no hay 35% probablemente también relajemos ese requisito.

Cuando haga los cambios los voy a taguear en un nuevo comentario para que sepan.

**Comment by tocococa** [comment]
@cotefon @juakoke ahí está actualizado el enunciado y el script, para que los revisen!
