### ISSUE TITLE
[Tarea 2] Crear datos

### ISSUE THREAD

**Issue by cotefon** [IIC2343/Syllabus-2022-1-S1#16]
Hola! una pregunta, es legal crear un nuevo array en .data? (esto es en la pregunta 1)

**Comment by tocococa** [comment]
Hola @cotefon, puedes hacer lo que quieras mientras no cambies los labels que nosotros utilizaremos como input.

**Comment by tocococa** [comment]
El valor de los labels que les pedimos que utilizen a modo de input va a cambiar, pero si defines más etiquetas en la sección .data no vamos a modificar su valor.
