### ISSUE TITLE
Uso de LRU en la tarea 2

### ISSUE THREAD

**Issue by gonzaloconcha** [IIC2343/Syllabus-2022-1-S1#17]
Hola, tengo una duda respecto al LRU para la tarea. No siento que tenga sentido el uso de *last reciently used* en caches de *direct mapping* ya que no se tiene que escoger cual dirección sacar, solo tendría sentido si usamos una cache *set associative*.
Gracias de antemano.

**Comment by tocococa** [comment]
Hola @gonzaloconcha, es verdad lo que dices que no hace demasiado sentido, pero para efectos del ejercicio la política de reemplazo y ubicación no es el foco, por lo que como tu dices, LRU al final no aporta en mucho.

Lo más importante es que vean porqué el programa está teniendo tan mal rendimiento, que sería similarmente malo en cualquier tipo de cache del mismo tamaño.
