### ISSUE TITLE
[Tarea 2] Output Parte 2

### ISSUE THREAD

**Issue by DomingoCarvajal** [IIC2343/Syllabus-2022-1-S1#18]
Hola! Tenía duda de donde guardar los valores finales de a, b, y r^2, debido a que se pide guardar los valores en los registros a0, a1 y a2 pero como son floats me hacia más sentido que fuera en fa0, fa1 y fa2, o algún otro registro de la FPU.

**Comment by tocococa** [comment]
Hola @DomingoCarvajal, puedes dejarlos en fa0, fa1 y fa2 si te queda más claro, pero en a0, a1 y a2 al final estarías guardando el mismo patrón de bits y para la corrección es equivalente, pero de todas maneras guárdalo en a0, a1 y a2.

**Comment by ssoliva** [comment]
Hola! No me queda claro cómo guarda floats en a0, a1 y a2. Utilizar mv o fmv.s me tira error de formato al intentar guardar en esos registros.
