### ISSUE TITLE
[Tarea 1] Testcases

### ISSUE THREAD

**Issue by Baelfire18** [IIC2343/Syllabus-2022-1-S1#19]
¡Hola! Actualizaron las notas de la tarea 1 en [el drive](https://docs.google.com/spreadsheets/d/1QpUVaaO2fRNUog68SJs_3q5SYpZ88jb48GTpEP-xlBw/edit#gid=732318100). A mí me comentaron en ambos preguntas de código que algunos testcases fallaban. Me gustaría preguntar si los puedes subir para ver en que fallaban mis códigos.
¡Gracias!

**Comment by tocococa** [comment]
Hola @Baelfire18, si quieres saber en que fallaba tu tarea o crees que no debería haber pasado por favor responde el formulario de recorrección de la T1 para ver eso.
