### ISSUE TITLE
[Tarea 2] Parte 2: duda output

### ISSUE THREAD

**Issue by mhrobles** [IIC2343/Syllabus-2022-1-S1#20]
es recomendable utilizar fmv o fcvt para pasar los resultados a a0, a1 y a2?, porque ambos funcionan de manera distinta, pero en esencia hacen lo mismo, por eso quisiera una confirmación si es posible

**Comment by tocococa** [comment]
Hola @mhrobles, usa `fmv`, ya que `fcvt` cambia el patrón de bits y `fmv` traspasa el patrón sin modificarlo.
