### ISSUE TITLE
[Tarea 2] Duda función fadd en un bucle

### ISSUE THREAD

**Issue by inarrgd** [IIC2343/Syllabus-2022-1-S1#21]
Hola!
Estoy intentando iterar sobre una serie floats para poder sumar cada uno de estos.
Utilizo el comando fadd.d dentro de un bucle de la siguiente manera:

"fadd.d f1,f1,f0", con f0 cambiando en cada iteración.

La cosa es que, al menos en operaciones de integers, la operación correspondiente me almacenaría en f1 la suma acumulada de todos los números al final del bucle, pero en el caso de esta instrucción señalada, se suma solamente el primer número y después cuando debiese ejecutarse la instrucción nuevamente, f1 queda con el mismo valor de float y no se realiza la suma (no me arroja error, solo pasa por la instrucción como su se hubiese ejecutado).

Quisiera saber si existe alguna manera de realizar esta operación con otra función, o si hay algo que estoy pasando por alto. Al utilizar fadd.s me retorna NaN las sumas.
Muchas gracias!

**Comment by tocococa** [comment]
Hola @inarrgd, si al usar `fadd.s` te retorna NaN, probablemente estás usando algo diferente a `flw` al cargar los números de punto flotante a la fpu desde memoria, no deberías necesitar usar números de precisión doble para esta tarea, sólo las instrucciones `*.s`.
