### ISSUE TITLE
Testeo Tarea 2

### ISSUE THREAD

**Issue by gonzaloconcha** [IIC2343/Syllabus-2022-1-S1#22]
Hola, quiero cambiar el .data del parte 1 pero no entiendo bien que hace **.space**. Me imagino que es el espacio que se le da en memoria pero no me hace mucho sentido los valores que tiene. ¿Hay tests ya hecho que podamos probar?

**Comment by tocococa** [comment]
Hola @gonzaloconcha, la directiva `.space n` reserva n bytes consecutivos de espacio vacío en memoria. Para la parte 1 no hay casos de prueba, deben mantener los valores del input.
