### ISSUE TITLE
[AYUDANTIA 7] Ejercicio Memoria virtual

### ISSUE THREAD

**Issue by juakoke** [IIC2343/Syllabus-2022-1-S1#23]
Viendo nuevamente el desarrollo de esta ayudantia, en el ejercicio de memoria virtual me confundí ¿Por qué a disco se le suma 1 al sacar la pagina de esta tabla y no cambia el bit de validez a 0? Por lo que veo es como si esa entrada siguiera siendo valida teniendo 8 entradas habilitadas (de un maximo de 8 por capacidad)

Otra pregunta de esta misma ayudantia, como calculan el tamaño de la cache en palabras?,  basicamente me confundí en esta slide:
![image](https://user-images.githubusercontent.com/48329030/167217820-0f6bf11d-202b-4b90-ad32-4ecf3a6d439a.png)

 Esto porque al calcular a mano 8KB = 8 * 2^10 * B = 8192 B, como byte = 8bits entonces 65.536 bits totales en la cache, luego eso dividido en el tamaño de una palabra (16 bits) me dio que se podian almacenar 4096 palabras en la cache(lo que es mayor a 4072). Luego cuando armo una formula para el tiempo tengo que:
(4072)* 10t + 9 * t * 4072 como primero todos miss y luego todos hits. En que me estoy equivocando?

**Comment by RenatoVWS** [comment]
Hola @juakoke!

Sobre tu segunda pregunta, efectivamente el tamaño de la caché debería ser de 4096 palabras lo que es mayor a 4072 que son las consultas que se nos piden realizar. Por esto, el computador va a traer una sola vez a la caché las palabras en esas direcciones de memoria y de ahí va a consultar a la caché las 9 veces siguientes.

En ese sentido, debes recordar que el computador trae bloques de palabras a la caché (no va a buscar una sola palabra) por el Principio de Localidad Espacial. Por esto, en el ejercicio el cálculo debería ser: 

64 (bloques de 64 palabras que trae a la caché) x 10t (tiempo consulta) + 10 (veces que nos piden consultar) x 4072 (cantidad de palabras a consultar) x t (tiempo caché hit)

Cualquier otra duda que tengas o algo que no quede claro me puedes decir.

Saludos!

**Comment by tatanramos** [comment]
Hola! 

Respecto a la pregunta de la memoria virtual, el bit de validez en las tablas de páginas solo indica si el mapeo de página virtual a marco físico es válido. En ese sentido, se suele dejar en 0 siempre que una página no tenga asignada un marco, pero una vez hecha esa asociación se mantiene en 1. Lo importante es que como esa entrada esta en el disco (por eso el bit de disco es 1), queda disponible el marco para asociar una página distinta.

**Comment by juakoke** [comment]
Gracias!
