### ISSUE TITLE
Tarea 2 Parte 1: Entregables

### ISSUE THREAD

**Issue by pureyesz** [IIC2343/Syllabus-2022-1-S1#24]
Hola, en la Parte 1 se pide explicar los cambios realizados y explicar correctamente a qué se debe el mal rendimiento del script original. Esto lo escribimos en el mismo script .asm de la Parte 1?

**Comment by tocococa** [comment]
Hola @pureyesz, sí, escríbelo como comentarios al principio del mismo script.

**Comment by Zetaku1** [comment]
@tocococa  respecto a esto mismo, comenté un poco el código para entender mejor el algoritmo, pero como el enunciado dice que deberemos comentar todos los cambios entonces talvez debería borrar los comentarios que no representan cambios?

**Comment by tocococa** [comment]
Hola @Zetaku1, no te preocupes por borrar esos comentarios, porque pueden ayudar en la corrección a ver que efectivamente entendiste que estabas haciendo.

**Comment by cotefon** [comment]
en esa misma pregunta, a que se refiere con: explicar porque el script pase la etapa del assembler?

**Comment by tocococa** [comment]
Hola @cotefon, son dos requisitos que suman 1 punto, se deben explicar los cambios realizados Y el script tiene que pasar el assembler, perdón si no se entendió la redacción.
