### ISSUE TITLE
[Tarea 3]: prange de numba

### ISSUE THREAD

**Issue by Baelfire18** [IIC2343/Syllabus-2022-1-S1#27]
En el [ejemplo de uso de numba entregado](https://github.com/IIC2343/Syllabus-2022-1-S1/blob/main/Tareas/T3/numba_example.ipynb) se utiliza este en 2 celdas de código. Una utiliza el iterador `range`, mientras que la otra utiliza `prange`. 
- ¿En la primera celda significa que no se paraleliza? Y de ser así ¿De que sirve tener el decorador entonces?
- En caso de que se parelelice en ambos, ¿cuál es el valor de `prange` entonces?

**Comment by tocococa** [comment]
Hola @Baelfire18, la primera celda si va a paralelizar, pero usar `range` en lugar de `prange` no necesariamente va a paralelizar el loop si este dependencias entre los loops. Al contrario, si se utiliza `prange` dentro de un loop que tiene dependencias entre cada loop, tendrías comportamiento indefinido, ya que Numba le asignará más de un worker independiente del loop.

Sobre tu segunda pregunta, `prange` no tienen un valor particular ya que es un iterador inmutable, y al ejecutar con Numba en el contexto `nopython` este se divide en nuevos rangos para cada worker asignado, pero si quieres indagar más te recomiendo revisar la implementación de Numba.
