### ISSUE TITLE
[TAREA 3] Output Parte 1

### ISSUE THREAD

**Issue by juakoke** [IIC2343/Syllabus-2022-1-S1#28]
En el enunciado dice que el resultado de la operación no debe variar, sin embargo en la solución propuesta el out1 es un array. Si en mi solución out 2 (paralelizado) es un numpy array igual a el de out1 pero en formato numpy, se considera bueno?

**Comment by tocococa** [comment]
Hola @juakoke, mientras el valor del resultado no cambie y se pueda leer, no importa el formato en que termine.
