### ISSUE TITLE
[TAREA 3] Mejora de performance y decorador njit

### ISSUE THREAD

**Issue by Deleon20** [IIC2343/Syllabus-2022-1-S1#29]
Hola! Tenia dos dudas con respecto a la parte 1 de la tarea. 

La primera es que tanta mejora se espera que haga nuestro codigo como para tener el puntaje en este item?

La segunda es que he visto en la documentacion de numba que en realidad usan mas el decorador `@njit` mas que `@njit(parallel = true)` hay algun problema con usar este?

Muchas gracias de antemano!

**Comment by tocococa** [comment]
Hola @Deleon20. la mejora en rendimiento depende del hardware en que estén corriendo sus tareas, pero yo esperaría al menos una reducción de 1.4x en el tiempo de ejecución. Si usar solo el decorador `@njit` sin la opción te funciona correctamente, no debería haber problemas.

**Comment by Deleon20** [comment]
Perfecto muchas gracias!
