### ISSUE TITLE
Tarea 1 - solicitud

### ISSUE THREAD

**Issue by Cadutodalcielo** [IIC2343/Syllabus-2022-1-S1#3]
Hola,
Tengo muchas dudas respecto a lo que hay que hacer en la parte 1 y 2 de la tarea, podrian pasar inputs y ouput de ejemplo? para por lo menos saber si estoy haciendo lo que se me pide.

Saludos

**Comment by tocococa** [comment]
Hola @Cadutodalcielo, a más tardar el miércoles les subiré un par de ejemplos por pregunta.
