### ISSUE TITLE
[Tarea 3] Parte 2 - Formato output y testcases

### ISSUE THREAD

**Issue by benjastraub** [IIC2343/Syllabus-2022-1-S1#31]
Hola, quería saber si hay que seguir algún formato en específico para el output.

También si subirán testcases para poder probar antes de entregar la tarea.

**Comment by tocococa** [comment]
Hola @benjastraub, el output no es relevante mientras la respuesta sea clara, pero a modo de ejemplo algo como `Instruccion X en la linea N` es suficiente.

Hoy en la tarde les subiré más ejemplos.

**Comment by arpincheira** [comment]
Hola, y es necesario dar el estado final de la memoria? Tipo, basta con poner: 
> No se mantiene coherencia en la línea `...`

o se debería poner

> El estado final de la memoria debiese ser `...` en lugar de `...`. No se mantiene coherencia en la línea `...`

como en los resultados de prueba entregados?
