### ISSUE TITLE
[Tarea 3] Parte 2 - Casos borde 

### ISSUE THREAD

**Issue by nicoguz** [IIC2343/Syllabus-2022-1-S1#32]
Hola! tengo una duda con respecto a un caso en particular. El caso es el siguiente:
![ej_duda](https://user-images.githubusercontent.com/53801690/173703320-847f56bd-1514-4647-864c-f2ea561478bd.png)
Considerando que no se mantiene consistencia entre caches, aquí la inconsistencia debería generarse al momento en que P0 lee la dirección de memoria en la segunda línea? O cuando se suma en P1 en la línea 3? O en su defecto, en la línea 4 cuando se intenta sumar en P0?

También, es necesario que consideremos estos casos en la tarea? Estoy un poco confundido con qué se considera "modificar el mismo recurso a la vez".

**Comment by tocococa** [comment]
Hola @nicoguz. acá deberías considerar que la inconsistencia podría ocurrir cuando P1 modifica el valor de A, ya que esa operación debería invalidar el valor de A en P0.

Lo que si no vas a ver en los tests, sería por ejemplo que en una misma línea dos o más procesadores intentaran modificar una variable asociada a la misma dirección de memoria, espero que esto aclare un poco tu segunda duda.

**Comment by nicoguz** [comment]
Perfecto, gracias!! 😊

**Comment by ssoliva** [comment]
Hola! Sólo para estar seguro entonces, de acuerdo a esto en los ejemplos que subieron:

+ Para el test 1 el error estaría en `SUB A, B` de la línea 3 del `P0` (ya que ahí se edita la memoria sin que se considere en los otros procesos) 
+ Para el test 2 el error estaría en `ADD  A, B` de la línea 3 del `P0`  (por la misma razón que antes)

Agradecería si me pueden confirmar o corregir para indicar bien la línea del error 😁

**Comment by tocococa** [comment]
Hola @ssoliva, en el archivo [ejemplos.md](https://github.com/IIC2343/Syllabus-2022-1-S1/tree/master/Tareas/T3/ejemplos/ejemplos.md) se indica la respuesta esperada.

**Comment by arpincheira** [comment]
Hola, para aquellos que quieran probar algo similar al caso borde descrito en esta issue, aquí les dejo un `.csv` de ejemplo:
```.csv
P0;P1;P2;P3;0x0000
MOV B, 1; MOV A, (0x0000); NOP; NOP; 1
MOV A, (0x0000); MOV B, 1; NOP; NOP; 2
NOP; ADD A, B; NOP; NOP;
ADD A, B;NOP; NOP; NOP;
NOP; NOP; NOP; NOP;
MOV (0x0000), A; NOP; NOP; NOP;
```
