### ISSUE TITLE
[Tarea 3]: Igualdad en parte 1

### ISSUE THREAD

**Issue by Baelfire18** [IIC2343/Syllabus-2022-1-S1#36]
Hola para el puntaje de la parte 1, el enunciado dice:

![image](https://user-images.githubusercontent.com/50716449/173936963-ef1923a1-78e4-40bd-8729-de466ca84716.png)

Esto último quiere decir que el output de todas las ejecuciones debe ser igual? Y si si como se comprueba esto? Lo que me pasa es que uno de da un array de float64 y el paralelizado me da un array de floats. Pero son exactamente los mismos numeros. Se consideran validos igual y solo debe imprimirlos o como se chequea su igualdad?

**Comment by tocococa** [comment]
Hola @Baelfire18, en la issue #28 se menciona lo que preguntas. Mientras el valor del resultado no cambie y este se pueda visualizar está bien.

**Comment by Baelfire18** [comment]
¿A que te refieres con que el resultado no cambie y se pueda visualizar?
Esto está bien?
![image](https://user-images.githubusercontent.com/50716449/173956365-12f38ceb-804a-4ca0-9888-7d8761f9099f.png)

**Comment by tocococa** [comment]
@Baelfire18, sip, eso está bien.
