### ISSUE TITLE
[Tarea 3] Parte 1 - Error uso de listas/arrays

### ISSUE THREAD

**Issue by mpbascunan** [IIC2343/Syllabus-2022-1-S1#38]
Hola, estaba intentando hacer la pregunta 1 con lista de listas, pero me aparece este error al hacer append: 
<img width="533" alt="errort3p1arqui" src="https://user-images.githubusercontent.com/53798683/174126940-0a874f4b-fe5f-4350-935d-267414c0d192.png">
Lo he buscado en internet pero lo que he encontrado lo he implementado y no me resulta, a qué se puede deber este error?
También intenté usar numpy array pero me salía un error similar con la función vstack()

**Comment by tocococa** [comment]
Hola @mpbascunan, Numba no trabaja bien con listas, te recomiendo trabajar con Numpy Arrays, que si funcionan (no se a que se puede deber tu error), o usar el datatype para listas que incluye Numba.
