### ISSUE TITLE
Duda orden de ejecución instrucciones pregunta 2

### ISSUE THREAD

**Issue by aljara97** [IIC2343/Syllabus-2022-1-S1#39]
Hola, tengo una duda respecto al orden en que se ejecutan las instrucciones de la pregunta 2. No me queda claro en el enunciado si es que se deben ejecutar todas las instrucciones de un procesador y luego seguir con todas las instrucciones de los procesadores siguientes (primero todas las del p0, luego todas las del p1 y así sucesivamente), o si cada fila representa un instante de tiempo y las instrucciones deben ejecutarse a la vez.

Agradecería si pudieran aclararme esta duda :(

**Comment by kraksiplus** [comment]
Al menos si tenemos en cuenta que la tarea se trata de paralelizacion, ¿me tinca que se estan ejecutando al mismo tiempo?

**Comment by tocococa** [comment]
Hola @aljara97, lo que dice @kraksiplus es lo correcto, cada línea del csv indica que se ejecutan 4 instrucciones en paralelo.
