### ISSUE TITLE
Contenidos I3

### ISSUE THREAD

**Issue by benjastraub** [IIC2343/Syllabus-2022-1-S1#43]
Hola!

Podrían subir el detalle de los contenidos que entrarán en la I3 por favor.

**Comment by Baelfire18** [comment]
@benjastraub yo no soy ayudante del ramo ni nada, pero según lo que tengo entendido y lo que hago mi resumen sería:

1. Paralelismo

1.1 Paralelismo en   el   chip
1.1.1 A   nivel   de   instrucciones: Técnicas  estáticas  (Very  Long  Instruction Word), Técnicas dinámicas (Arquitecturas Superescalares)
1.1.2 Multithreading

1.2         Multiprocesadores
1.2.1          SMP   o   UMA
1.2.2          DSM   o   NUMA
1.2.3          Protocolos   de   coherencia   de   caché
1.2.4          Protocolo   write-trough
1.2.5          Protocolo   write-back
1.2.6          Protocolo   MESI   (en   Core   i7)

1.3 GPUs
1.3.1          SIMT
1.3.2          Memoria

2.  ISA:   Arquitectura   del   Set   de Instrucciones

2.1         Tipos   de   registro
2.2         Formato   de   las   instrucciones
2.3         Modelo   de   memoria
2.4         Direccionamiento
2.5         Paradigma  Complex  Instruction Set   Computer   (CISC)
2.6.         Paradigma  Reduced  Instruction  Set Computer   (RISC)

**Comment by tocococa** [comment]
Hola @benjastraub, lo que indicó @Baelfire18 es más o menos correcto, la I3 no es un examen, por lo que el foco de las preguntas será en aquellos contenidos que no han sido evaluados en la I1 e I2.
