### ISSUE TITLE
[Contenido I3]: Simparallel

### ISSUE THREAD

**Issue by Baelfire18** [IIC2343/Syllabus-2022-1-S1#44]
Hola tenía un par de preguntas sobre la materia de la I3, dado el siguiente diagrama mostrado en ayudantía:
![image](https://user-images.githubusercontent.com/50716449/175359356-0b2e398c-ef19-440a-8003-a5715c8a8ad0.png)

1. En el caso de la T3 parte 2: Simparallel que tipo de paralelismo es? Sería SIMD, es decir, Single Instruction Multiple Data.
2. GPU sería del tipo SIMD (Single Instruction Multiple Data) o más bien del tipo SIMT (Single Instruction Multiple Threads) ?
3. Multiprocesadores son MIMD cierto?

**Comment by tocococa** [comment]
Hola @Baelfire18, el paralelismo de la T3.2 sería MIMD, ya que múltiples instrucciones con diferentes datos ejecutando en paralelo.

Una GPU básica es un procesador SIMD, pero las GPUs modernas suelen ser SIMT, donde cada thread podría verse como una ejecución SIMD.

Los sistemas MISD no corresponde a un multiprocesador, ya que estos podría trabajar con diferentes datos en paralelo. En ese ejmplo se menciona el procesador del transbordador, ya que este tenía múltiples procesos monitoreando un único stream de datos provenientes de los sensores del transbordador. No es precisamente un único dato, pero cada thread procesaba un mismo batch de datos.

**Comment by Baelfire18** [comment]
@tocococa la ultima pregunta era por MIMD siendo multiprocesador

**Comment by tocococa** [comment]
Perdón, leí MISD en vez de MIMD, pero si, un multiporocesador sería MIMD.
