### ISSUE TITLE
[Ejercicio Ayudantía 12]

### ISSUE THREAD

**Issue by Baelfire18** [IIC2343/Syllabus-2022-1-S1#45]
Hola, en la ayudantía 12, en la diapo 26 se resuelve un ejercicio de multithreading con granularidad fina:
![image](https://user-images.githubusercontent.com/50716449/175835411-4b322504-5f1e-437d-af74-3d4951edd9c0.png)

En cada thread hay stalls de 2 tiempos, pero esto no causa problema, ya que como son 3 threads, en ese tiempo de stall ocurren los otros.

¿Mi pregunta es que pasaría si hubieran 3 stalls? ¿O esto no sería posible? Inserto foto de caso:
![image](https://user-images.githubusercontent.com/50716449/175835534-db76562f-5870-469d-9038-e247cdab9ed2.png)

**Comment by Baelfire18** [comment]
Y para granularidad gruesa tengo la misma pregunta. Que pasa si al momento de volver a llamar a un thread la siguiente instruccion (que no es un stall, claro) aún no está disponible por tiempo?
![image](https://user-images.githubusercontent.com/50716449/175835833-6e8b9e50-0288-4182-8038-32aec814f4be.png)

**Comment by Baelfire18** [comment]
Tambien para cualquiera de los 2 tipos de granularidades que se hace cuando se acaban las intrucciones de 1 o más pipelines (sin que sean todos claro). Creo que basicamente se resumen la pregunta en: ¿que hacer con stalls extra en los 2 casos de granularidades? (si queda solo 1 thread podría intuir, pero si quedan 2 no sé que se haría)

**Comment by tocococa** [comment]
Hola @Baelfire18, @fcbahamondes, sobre que ocurre al agregar 3 stalls en lugar de 2, tendrías un stall en la casilla que marcaste con ?, ya que ninguno de los procesos está listo para entrar a ejecutar y se pierde ese ciclo. En el caso de la granularidad gruesa, podrían ocurrir dos cosas, o pierdes el ciclo ya que el hilo que debiese ejecutar no está listo, o permites que un hilo que si ya terminó sus stalls entre a ejecutar y el hilo al que le correspondía ese turno espera al próximo grano.

Si se acaba un hilo, continúan ejecutando los hilos restantes bajo las reglas que mecioné en el párrafo anterior.

**Comment by Baelfire18** [comment]
@tocococa 
Con respecto a:
1) Entonces si A2 y A3 de la primera fila se alejan mucho de A1, habrian muchisimos stalls hasta que lleguen recien a A2 y A3? Aunque sea factible seguir en los otros threads, dado que se pierden ciclos hasta que este disponible para el primero?

2) De que depende cual de las cosas pasen? Y en el primer caso (` pierdes el ciclo ya que el hilo que debiese ejecutar no está listo`), podria ocurrir que hay mutiples stalls esperando el ciclo valido como menciono en el párrafo anterior?

**Comment by tocococa** [comment]
Claro, en el caso 1 podrías perder varios ciclos al alternar entre los 3 hilos mientras A* sigue esperando. Sobre tu segundo punto, no entiendo muy bien a que te refieres, pero esas son particularidades de la ISA que no se pueden asumir a priori.

**Comment by Baelfire18** [comment]
Oka! Muchas gracias Tomás! 💯

**Comment by fcbahamondes** [comment]
Me queda una duda en el caso de las granularidades. En el caso de la fina, tendría un stall en el casillero del signo "?", pero luego de eso, se siguen completando con stalls hasta que A2 pueda ejecutarse o me puedo saltar al B2.  En el caso de la granularidad gruesa, de que depende elegir si cambiar de thread o esperar al que le tocaba. En caso de cambiar de thread, por ejemplo: ejecuto B3 y B4, después debo de intentar con el thread que le correspondia el turno o sigo con los Cs?

**Comment by tocococa** [comment]
Hola @fcbahamondes, en el caso de la granularidad fina, en `?` tendrías un stall y luego continuaría con `B2`. En el caso de la granularidad gruesa, el cambiar o no probablemente dependería de si el hilo al que le toca ejecutar esta stalled o no. Que thread ejecuta después de eso también depende, podría ser B o C.

**Comment by fcbahamondes** [comment]
gracias!!!

**Comment by jnvillarroel** [comment]
@tocococa que pasaria si llegamos al final de los threads y por ejemplo solo me quedan elementos en A, de la forma 
A2 A3 Stall A4
Por su parte B y C ya terminaron.... tendría que cambiarme de thread igualmente? -->  A2 A3 Stall Stall Stall A4
ó bastaría con esperar en A, sin tener que cambiarse --> A2 A3 Stall A4
