### ISSUE TITLE
[Ejercicio Ayudantía 14]

### ISSUE THREAD

**Issue by Baelfire18** [IIC2343/Syllabus-2022-1-S1#46]
¿En caso de querer realizarse este ejercicio con memory-memory, como sería?
![image](https://user-images.githubusercontent.com/50716449/176035750-c0655a7b-eda7-4990-904c-6750102a2de1.png)

Por lo que entendí de memory-memory: `Las instrucciones leen de memoria, modifican el dato, y luego guardan en memoria, con un solo opcode.`

Es decir (si el máximo de operando son 3), una respuesta posible podría ser algo así:

```ruby
Add A, B, C
Add D, A, B
Sub E, D, C
```

O sería algo distinto? Muchas gracias de ante mano

**Comment by tocococa** [comment]
Hola @Baelfire18, lo que indicas está bien para una ejecución en una ISA memoria-memoria, aunque históricamente las instrucciones memoria-memoria funcionan con 2 operandos.

**Comment by Baelfire18** [comment]
@tocococa como seria memoria-memoria con 2 operandos?
Algo así?
```rb
MOV A, B
ADD A, C
MOV D, A
ADD D, B
MOV E, D
SUB E, C
```

O se te ocurre una forma sin utilizar `MOV`

**Comment by tocococa** [comment]
@Baelfire18, probablemente tendrías que usar MOV para lograr el resultado, o mandar a 0 el registro A y sumarle B y C. El tamaño del código probablemente sería algo como dices tu, pero en el caso de memoria-memoria no tienes bits para el tamaño de los registros, sería algo así como `opcode+dir_mem_1+dir_mem_2` para cada instrucción en un assembly muy básico que solo toma dos operandos.

**Comment by Baelfire18** [comment]
Gracias! 🚀
