### ISSUE TITLE
Ayudantías disponibles

### ISSUE THREAD

**Issue by inarrgd** [IIC2343/Syllabus-2022-1-S1#47]
Hola!
Buscando material de estudio, noté un salto de la ayudantía 12 a la 14 en los archivos de Canvas. Hay ayudantía 13?
No sé de dónde practicar ejercicios para la prueba, por si me pueden orientar por favor.

Muchas gracias, saludos

**Comment by IgnaciaJ** [comment]
Hola! Tengo la misma duda

**Comment by DanielaCorral** [comment]
Hola! Tengo la impresión que la ayudantía 13 sí existió :( porque la ayudantía 12 que subieron a Canvas se hizo el 3 de junio y la ayudantía 14 se hizo el 17 de junio. El viernes 10 hubo ayudantía también (debería ser la 13), o estoy mal?

**Comment by tocococa** [comment]
Perdoooon, si, me habia confundido con otro cambio de números, altiro subo las diapos.
