### ISSUE TITLE
[Ejercicio Ayudantía 13]

### ISSUE THREAD

**Issue by valeeeriquelme** [IIC2343/Syllabus-2022-1-S1#48]
Hola, 
en relación a un ejercicio de la ayudantía 13 (adjunto imagen) no me quedó claro por qué la ejecución correcta es en ese orden. Luego, muestra una ejecución incorrecta y menciona que eso no asegura la coherencia en la cache y tampoco me queda claro por qué, porque al final el protocolo que se sigue es el mismo que en la versión correcta (cuando un procesador hace un cambio, el otro procesador se actualiza). 

Gracias de antemano 👽✌️
versión correcta:
![WhatsApp Image 2022-06-30 at 1 48 48 AM](https://user-images.githubusercontent.com/37518300/176721669-d7830a1a-b35e-4583-b1c0-d9dfeffb9e8e.jpeg)

versión incorrecta: 
![image](https://user-images.githubusercontent.com/37518300/176723266-fc7d56a4-352a-4b0e-a975-d9ecc01c198b.png)

**Comment by jnvillarroel** [comment]
En un caso asi, tenemos la libertad de reordenar las instrucciones para que un procesador no sobreescriba lo hecho por el otro? En que caso si y en que caso nos conviene respetar al pie de la letra el orden entregado?

**Comment by tocococa** [comment]
Hola @jnvillarroel, cualquier caso de este estilo estaría debidamente explicado que es lo que tienen que hacer.
