### ISSUE TITLE
Protocolo MESI

### ISSUE THREAD

**Issue by IgnaciaJ** [IIC2343/Syllabus-2022-1-S1#49]
Hola! Tenía una duda con el llenado de estados en protocolo MESI. ¿ Está bien hacer las instrucciones por separado?(así como se muestra en la ayudantía 13) 
es decir, en este caso cuando tengo dos procesadores paralelos las instrucciones pueden ejecutarse de forma separada o deben ser necesariamente juntas bajo un mismo ciclo de reloj(osea que las instrucciones se ejecuten en la misma línea de la tabla MESI)? 

<img width="1043" alt="image" src="https://user-images.githubusercontent.com/69643709/176787440-9ae9dde7-0617-44dc-8235-ae95966b4f12.png">

Muchas gracias!

**Comment by tocococa** [comment]
Hola @IgnaciaJ, puedes hacerlo como se muestra en la ayudantía una luego de la otra, porque de todas formas no debería ocurrir que dos instrucciones tratan de modificar la misma variable a la vez.

**Comment by IgnaciaJ** [comment]
Gracias!!
