### ISSUE TITLE
[Tarea 1] Centroides

### ISSUE THREAD

**Issue by Baelfire18** [IIC2343/Syllabus-2022-1-S1#5]
Hola,
En la parte 1 piden calcular el centroide de ambas figuras y solamente retornar 1 respuesta en a0, a1 y a2. No entiendo eso de calcular centride para ambos y solo retornar una respuesta.

¿El enunciado no querrá decir calcular el centro de masa de todo?

**Comment by tocococa** [comment]
Si.

**Comment by Cristofernandez** [comment]
Hola, con promedio se refiere a algo como sumar y dividir lo que da en la cantidad de figuras?

**Comment by tocococa** [comment]
Hola @Cristofernandez, si, la fórmula es algo similar a
![image](https://user-images.githubusercontent.com/22779371/161616290-2f1bf1ef-b236-4e05-9936-dd34c57f520a.png)
Donde a puede ser x, y o z, i indica el cuerpo y C es la coordenada del centroide en ese eje y M es la masa.
