### ISSUE TITLE
[Tarea 1] - Plazo

### ISSUE THREAD

**Issue by inarrgd** [IIC2343/Syllabus-2022-1-S1#6]
Hola!
Considerando que el viernes pasado vimos recién RISC-V en la ayudantía. Es posible aplazar la fecha de entrega?
De antemano gracias,
Salu2

**Comment by vikicontardo** [comment]
Me sumo a la petición también 🙏🏻 Sería de gran ayuda tiempo extra para poder analizar la tarea y utilizar la materia vista el lunes en clases para enfrentarla. De antemano muchísimas gracias equipo docente 💛

**Comment by jahernandez2** [comment]
Me sumo a la petición, sería de mucha ayuda dados los argumentos expuestos.

**Comment by pwillmer** [comment]
Comparto lo dicho por mis compañeros, me sumo a la petición.

**Comment by mhrobles** [comment]
yo también me sumo a la petición, esta semana también tengo 2 entregas mas de trabajos para el viernes, una interrogación el jueves y un laboratorio evaluado para el viernes también :c

**Comment by kraksiplus** [comment]
comparto la peticion :D

**Comment by Nicksoliss** [comment]
Me sumo a la petición, recién tuvimos la ayudantía de RISC-V hace una semana y la tarea tiene un grado de complejidad no menor, así que un plazo extra sería de gran ayuda :)

**Comment by CatalinaGoldsack** [comment]
Me sumo a la petición!

**Comment by pureyesz** [comment]
Me sumo a la petición y comparto lo que han dicho mis compañeros.
