### ISSUE TITLE
Visualización emulador en Mac

### ISSUE THREAD

**Issue by fcbahamondes** [IIC2343/Syllabus-2022-1-S1#7]
Hola, estoy intentado correr un código en el emulador pero no puedo visualizar el execute. En la parte de messages me aparece que la operación fue completada satisfactoriamente pero no puedo ver el dellate.

<img width="1031" alt="Captura de pantalla 2022-04-05 a las 12 58 02" src="https://user-images.githubusercontent.com/80771151/161809263-3f3f2eb1-2f95-44f4-9032-71278e679b54.png">

**Comment by tocococa** [comment]
Hola @fcbahamondes, creo que nunca había visto comportamiento parecido, tres cosas, tienes tu instalación de Java actualizada? Es un M1? y por último, le diste permiso a RARS para que acceda a tu sistema de archivos?

**Comment by tocococa** [comment]
Hola @CatalinaGoldsack, si ya probaste todo lo que indiqué, lo último que podrías intentar es probar con un release diferente de Java o [del emulador](https://github.com/TheThirdOne/rars/releases). Si nada de eso funciona, la última opción sería que instales una máquina virtual con Windows, instales Java dentro de la VM y luego corras el emulador desde ahí. ¿Estás usando MacOS 21.0?

**Comment by fcbahamondes** [comment]
Hola, la solución es mucho más simple. Hay que habilitar la visualización en la parte de settings.

**Comment by tocococa** [comment]
@fcbahamondes puedes decirme exactamente dónde habilitaste la visualización? Hay otro estudiante con el mismo problema y no veo dónde está la opción. Gracias!

**Comment by fcbahamondes** [comment]
Hola, hice un cambio en esta parte en la primera, antes no me aparecia con el ticket.


<img width="533" alt="Captura de Pantalla 2022-05-13 a las 17 58 38" src="https://user-images.githubusercontent.com/80771151/168394772-1def8c79-29c3-4dca-8591-c6420ad9613e.png">
