### ISSUE TITLE
{Tarea 1] Objetivo

### ISSUE THREAD

**Issue by inarrgd** [IIC2343/Syllabus-2022-1-S1#8]
Hola! 
Tengo una duda, no sé si entiendo bien el trasfondo de la tarea, lo intentaré ejemplificar con el punto 2.1. Por favor corregirme si me equivoco. La idea es que, teniendo puntos enteros que nos dan como inputs de coordenadas para la ubicación de los vértices de dos figuras distintas, nosotros podamos generar, con el algoritmo que elegimos después de investigar, la forma de realizar suma, resta, división y multiplicación de números de punto flotante para calcular el centro de masa de ambas figuras ?

Siguiendo con la pregunta de arriba, otra duda, RISC-V no cuenta con FPU? o si, pero hay que ignorarla y realizar la implementación propia del algoritmo. (Acabo de encontrar que existen funciones fadd, fsub, etc)

Gracias!
Saludos

**Comment by tocococa** [comment]
Hola  @inarrgd, respecto a tu primera pregunta, sí, deben aproximar el resultado de dichas operaciones de punto flotante utilizando la ALU de Risc-v y trabajando con números enteros o alguna implementación diferente. Esta implementación va a tener un margen de error, como habrás visto en el video que aparece en la introducción, pero depende de su implementación, por lo que es importante que sus soluciones de los ítems 2.1 y 2.2 sean acorde con su informe.

Sobre tu segunda pregunta, sí, Risc-v tiene una extensión (RV32F) para punto flotante, pero no deben utilizar estas instrucciones para esta tarea.
