### ISSUE TITLE
Orden ppt vistos en clases

### ISSUE THREAD

**Issue by pwillmer** [IIC2343/Syllabus-2022-1-S1#9]
Hola! en canvas los ppt están ordenados por tema en modulos, pero no están en orden según lo visto en clases por lo que entiendo. Revisando en la carpeta archivos, se subieron en este orden. 

1.	Lógica digital I
2.	Lógica digital II
3.	Aritmética y números I
4.	Lógica digital III
5.	Aritmética y números II
6.	Lógica digital IV
7.	Procesador I
8.	Procesador II
9.	Aritmética y números III
10.	Procesador III (subrutinas)
11.	Aritmética y números IV
12.	Memoria I

¿Es este el orden realmente? ¿Podrían crear una sección en canvas considerando la fecha que se vió la clase por favor?

**Comment by tatanramos** [comment]
Hola! Efectivamente están agrupados por módulos ya que algunos temas son importantes para entender los demás sin tener un orden lógico. Voy a ver si hay alguna forma de dejarlos ordenados de acuerdo a la fecha de subida (No soy experto en canvas jajaja).

**Comment by fcbahamondes** [comment]
Hola, hasta que ppt entra en la prueba de la próxima semana??

**Comment by tatanramos** [comment]
Hola, debería entrar hasta punto flotante (incluyendolo). De todas formas se mandará un anuncio con la info oficial
